/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import padraoNovo.JDlgPesquisProdutoNovo;
import padraoNovo.JDlgPesquisaVendedorNovo;
import consultas.*;

/**
 *
 * @author 08060243136
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Sistemas de Vendas");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuCadastro_efb = new javax.swing.JMenu();
        jMnuUsuarios_efb = new javax.swing.JMenuItem();
        jMnuCliente_efb = new javax.swing.JMenuItem();
        jMnuProduto_efb2 = new javax.swing.JMenuItem();
        jMnuVendedor_efb2 = new javax.swing.JMenuItem();
        jSeparator1_efb = new javax.swing.JPopupMenu.Separator();
        jMnuSair_efb = new javax.swing.JMenuItem();
        jMnuMovimento_efb = new javax.swing.JMenu();
        jMenuVendaEfb = new javax.swing.JMenuItem();
        jMnuConsultas_efb = new javax.swing.JMenu();
        jMnuConsulCliente = new javax.swing.JMenuItem();
        jMnuConsulProduto = new javax.swing.JMenuItem();
        jMnuConsulUsuar = new javax.swing.JMenuItem();
        jMnuConsultVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/central-de-ajuda.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMnuCadastro_efb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registro.png"))); // NOI18N
        jMnuCadastro_efb.setMnemonic('C');
        jMnuCadastro_efb.setText("Cadastros");

        jMnuUsuarios_efb.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios_efb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/users.png"))); // NOI18N
        jMnuUsuarios_efb.setMnemonic('U');
        jMnuUsuarios_efb.setText("Usuários");
        jMnuUsuarios_efb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuarios_efbActionPerformed(evt);
            }
        });
        jMnuCadastro_efb.add(jMnuUsuarios_efb);

        jMnuCliente_efb.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuCliente_efb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        jMnuCliente_efb.setMnemonic('c');
        jMnuCliente_efb.setText("Cliente");
        jMnuCliente_efb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuCliente_efbActionPerformed(evt);
            }
        });
        jMnuCadastro_efb.add(jMnuCliente_efb);

        jMnuProduto_efb2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProduto_efb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produtos.png"))); // NOI18N
        jMnuProduto_efb2.setMnemonic('P');
        jMnuProduto_efb2.setText("Produto Novo");
        jMnuProduto_efb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProduto_efb2ActionPerformed(evt);
            }
        });
        jMnuCadastro_efb.add(jMnuProduto_efb2);

        jMnuVendedor_efb2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendedor_efb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendedor.png"))); // NOI18N
        jMnuVendedor_efb2.setMnemonic('V');
        jMnuVendedor_efb2.setText("Vendedor Novo");
        jMnuVendedor_efb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendedor_efb2ActionPerformed(evt);
            }
        });
        jMnuCadastro_efb.add(jMnuVendedor_efb2);
        jMnuCadastro_efb.add(jSeparator1_efb);

        jMnuSair_efb.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair_efb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair.png"))); // NOI18N
        jMnuSair_efb.setMnemonic('r');
        jMnuSair_efb.setText("Sair");
        jMnuSair_efb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSair_efbActionPerformed(evt);
            }
        });
        jMnuCadastro_efb.add(jMnuSair_efb);

        jMenuBar1.add(jMnuCadastro_efb);

        jMnuMovimento_efb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lojas.png"))); // NOI18N
        jMnuMovimento_efb.setText("Movimento");

        jMenuVendaEfb.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuVendaEfb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendas.png"))); // NOI18N
        jMenuVendaEfb.setText("Venda");
        jMenuVendaEfb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendaEfbActionPerformed(evt);
            }
        });
        jMnuMovimento_efb.add(jMenuVendaEfb);

        jMenuBar1.add(jMnuMovimento_efb);

        jMnuConsultas_efb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consulta-de-pesquisa.png"))); // NOI18N
        jMnuConsultas_efb.setText("Consulta");

        jMnuConsulCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        jMnuConsulCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar users.jpg"))); // NOI18N
        jMnuConsulCliente.setText("Consulta Cliente");
        jMnuConsulCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsulClienteActionPerformed(evt);
            }
        });
        jMnuConsultas_efb.add(jMnuConsulCliente);

        jMnuConsulProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        jMnuConsulProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lista-de-controle.png"))); // NOI18N
        jMnuConsulProduto.setText("Consulta Produto");
        jMnuConsulProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsulProdutoActionPerformed(evt);
            }
        });
        jMnuConsultas_efb.add(jMnuConsulProduto);

        jMnuConsulUsuar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK));
        jMnuConsulUsuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/publico-alvo.png"))); // NOI18N
        jMnuConsulUsuar.setText("Consulta Usuario");
        jMnuConsulUsuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsulUsuarActionPerformed(evt);
            }
        });
        jMnuConsultas_efb.add(jMnuConsulUsuar);

        jMnuConsultVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jMnuConsultVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analise.png"))); // NOI18N
        jMnuConsultVenda.setText("Consulta Vendedor");
        jMnuConsultVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultVendaActionPerformed(evt);
            }
        });
        jMnuConsultas_efb.add(jMnuConsultVenda);

        jMenuBar1.add(jMnuConsultas_efb);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(0, 204, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuUsuarios_efbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuarios_efbActionPerformed
        JDlgUsuarios jDlgUsuarios = new JDlgUsuarios(null, true);
        jDlgUsuarios.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuUsuarios_efbActionPerformed

    private void jMnuSair_efbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSair_efbActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuSair_efbActionPerformed

    private void jMnuCliente_efbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuCliente_efbActionPerformed
        JDlgCliente jDlgCliente = new JDlgCliente(null, true);
        jDlgCliente.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuCliente_efbActionPerformed

    private void jMnuProduto_efb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProduto_efb2ActionPerformed
        // TODO add your handling code here:
        JDlgPesquisProdutoNovo jDlgPesquisProdutoNovo = new JDlgPesquisProdutoNovo(null, true);
        jDlgPesquisProdutoNovo.setVisible(true);
    }//GEN-LAST:event_jMnuProduto_efb2ActionPerformed

    private void jMnuVendedor_efb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendedor_efb2ActionPerformed
        // TODO add your handling code here:
        JDlgPesquisaVendedorNovo jDlgPesquisaVendedorNovo = new JDlgPesquisaVendedorNovo(null, true);
        jDlgPesquisaVendedorNovo.setVisible(true);
    }//GEN-LAST:event_jMnuVendedor_efb2ActionPerformed

    private void jMnuConsultVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultVendaActionPerformed
        // TODO add your handling code here:
        JDlgConsultaVendedor consultaVendedor=new JDlgConsultaVendedor(null, true);
        consultaVendedor.setVisible(true);
      
    }//GEN-LAST:event_jMnuConsultVendaActionPerformed

    private void jMnuConsulUsuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsulUsuarActionPerformed
        // TODO add your handling code here:
        JDlgConsultaUsuario consultaUsuario = new JDlgConsultaUsuario(null, true);
        consultaUsuario.setVisible(true);
    }//GEN-LAST:event_jMnuConsulUsuarActionPerformed

    private void jMnuConsulProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsulProdutoActionPerformed
        // TODO add your handling code here:
        JDlgConsultaProduto consultaProduto = new JDlgConsultaProduto(null, true);
        consultaProduto.setVisible(true);
    }//GEN-LAST:event_jMnuConsulProdutoActionPerformed

    private void jMnuConsulClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsulClienteActionPerformed
        // TODO add your handling code here:
        JDlgConsultaCliente ConsultaCliente = new JDlgConsultaCliente(null, true);
        ConsultaCliente.setVisible(true);
    }//GEN-LAST:event_jMnuConsulClienteActionPerformed

    private void jMenuVendaEfbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendaEfbActionPerformed
        // TODO add your handling code here:
        JDlgVendas jDlgVendas=new JDlgVendas(null, true);
        jDlgVendas.setVisible(true);
    }//GEN-LAST:event_jMenuVendaEfbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuVendaEfb;
    private javax.swing.JMenu jMnuCadastro_efb;
    private javax.swing.JMenuItem jMnuCliente_efb;
    private javax.swing.JMenuItem jMnuConsulCliente;
    private javax.swing.JMenuItem jMnuConsulProduto;
    private javax.swing.JMenuItem jMnuConsulUsuar;
    private javax.swing.JMenuItem jMnuConsultVenda;
    private javax.swing.JMenu jMnuConsultas_efb;
    private javax.swing.JMenu jMnuMovimento_efb;
    private javax.swing.JMenuItem jMnuProduto_efb2;
    private javax.swing.JMenuItem jMnuSair_efb;
    private javax.swing.JMenuItem jMnuUsuarios_efb;
    private javax.swing.JMenuItem jMnuVendedor_efb2;
    private javax.swing.JPopupMenu.Separator jSeparator1_efb;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
