/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consultas;

import dao.ClienteDao_efb;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import tools.Util;
import javax.swing.JOptionPane;

public class JDlgConsultaCliente extends javax.swing.JDialog {

    /**
     * Creates new form JDlgPesquisaCliente
     */
    // JDlgCliente jDlgCliente;
    Util util;
    ConsultaCliente_efb pesquisarCliente;
    ClienteDao_efb clienteDao;
    List lista;
    private static final Logger LOGGER = Logger.getLogger(ClienteDao_efb.class.getName());

    public JDlgConsultaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Consultar Cliente");
        pesquisarCliente = new ConsultaCliente_efb();
        clienteDao = new ClienteDao_efb();

        lista = new ArrayList();
        pesquisarCliente.setList(lista);
        jTable1.setModel(pesquisarCliente);
    }

    /*    public void setTelaAnterior(JDlgCliente jDlgCliente) {
        this.jDlgCliente = jDlgCliente;

    }*/
    public void Limpar() {
        util.limparCampos(jTxtEstado_Efb1, jTxtNome_Efb, jCmbSexo_efb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnCancelar_efb = new javax.swing.JButton();
        jBtnOk_efb = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtNome_Efb = new javax.swing.JTextField();
        jBtnPesquisar_efb = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTxtEstado_Efb1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCmbSexo_efb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBtnCancelar_efb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair.png"))); // NOI18N
        jBtnCancelar_efb.setText("Cancelar");
        jBtnCancelar_efb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_efbActionPerformed(evt);
            }
        });

        jBtnOk_efb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        jBtnOk_efb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOk_efbActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jBtnPesquisar_efb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisa-global.png"))); // NOI18N
        jBtnPesquisar_efb.setText("Pesquisar");
        jBtnPesquisar_efb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisar_efbActionPerformed(evt);
            }
        });

        jLabel3.setText("Sexo:");

        jLabel4.setText("Estado:");

        jCmbSexo_efb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnOk_efb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnCancelar_efb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnPesquisar_efb)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtNome_Efb, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmbSexo_efb, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtEstado_Efb1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNome_Efb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbSexo_efb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEstado_Efb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnCancelar_efb)
                        .addComponent(jBtnPesquisar_efb))
                    .addComponent(jBtnOk_efb, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelar_efbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_efbActionPerformed
        // TODO add your handling code here:
        if (util.pergunta("Deseja Cancelar ?")) {
            setVisible(false);
        } else {
            util.mensagem("Selecione uma linha");
        }
    }//GEN-LAST:event_jBtnCancelar_efbActionPerformed

    private void jBtnOk_efbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOk_efbActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha!");
        }
        setVisible(false);
    }//GEN-LAST:event_jBtnOk_efbActionPerformed

    private void jBtnPesquisar_efbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisar_efbActionPerformed
        // TODO add your handling code here:
        clienteDao = new ClienteDao_efb();
        
        if (!jTxtNome_Efb.getText().isEmpty() && jTxtEstado_Efb1.getText().isEmpty() && jCmbSexo_efb.getSelectedItem().equals("")) {
            // Se somente o campo de nome estiver preenchido e o campo de estado estiver vazio, e nenhum item estiver selecionado no JComboBox
            LOGGER.info("Consultando por nome.");
            lista = (List) clienteDao.listNome(jTxtNome_Efb.getText());
            pesquisarCliente.setList(lista);
        } else if (jTxtNome_Efb.getText().isEmpty() && jTxtEstado_Efb1.getText().isEmpty() && jCmbSexo_efb.getSelectedItem().equals("")) {
            LOGGER.info("Consultando todos os clientes.");
            lista = clienteDao.listAll();
            pesquisarCliente.setList(lista);
        } else if (jTxtNome_Efb.getText().isEmpty() && !jTxtEstado_Efb1.getText().isEmpty() && jCmbSexo_efb.getSelectedItem().equals("")) {
            // Se somente o campo de estado estiver preenchido e o campo de nome estiver vazio, e nenhum item estiver selecionado no JComboBox
            LOGGER.info("Consultando por estado.");
            lista = clienteDao.listPorEstado(jTxtEstado_Efb1.getText());
            pesquisarCliente.setList(lista);
        } else if (!jTxtNome_Efb.getText().isEmpty() && !jTxtEstado_Efb1.getText().isEmpty() && !jCmbSexo_efb.getSelectedItem().equals("")) {
            // Se ambos os campos de nome e estado estiverem preenchidos e um item estiver selecionado no JComboBox
            LOGGER.info("Consultando por nome, estado e sexo.");
            lista = clienteDao.listPorNomeEEstadoESexo(jTxtNome_Efb.getText(), jTxtEstado_Efb1.getText(), (String) jCmbSexo_efb.getSelectedItem());
            pesquisarCliente.setList(lista);
        } else {
            // Se nenhuma das condições acima for atendida
            LOGGER.warning("Nenhuma condição de consulta correspondente encontrada.");
        }
    }//GEN-LAST:event_jBtnPesquisar_efbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgConsultaCliente dialog = new JDlgConsultaCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar_efb;
    private javax.swing.JButton jBtnOk_efb;
    private javax.swing.JButton jBtnPesquisar_efb;
    private javax.swing.JComboBox<String> jCmbSexo_efb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtEstado_Efb1;
    private javax.swing.JTextField jTxtNome_Efb;
    // End of variables declaration//GEN-END:variables
}
